[package]
name = "wireguard-faketap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
boringtun = "0.6.0"

[build-dependencies]
cc = "~1"
cargo-emit = "0.2.1"
