[package]
name = "wireguard-faketap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
boringtun = "0.6.0"
nix = { version = "0.27", features = ["ioctl"] }
